Update face detection for the Pillow upgrade in e69c569749c83762f
Without this change, we get an error like:

  File "/data/vhost/tusrepresentanteslocales.co.cr/yournextrepresentative/moderation_queue/faces.py", line 25, in detectFaces
    cv.SetData(cv_im, im.tostring(), im.size[0])
  File "/data/vhost/tusrepresentanteslocales.co.cr/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 699, in tostring
    "Please call tobytes() instead.")
   Exception: tostring() has been removed. Please call tobytes() instead.