Quieten a Sass deprecation warning from Foundation 5.5.3
The following deprecation warning from sass version 3.4.21 (caused by
the Foundation 5.5.3 source) causes collectstatic to fail:

  pipeline.exceptions.CompilerError: DEPRECATION WARNING on line 78 of /home/mark/yournextrepresentative/static/foundation/scss/foundation/components/_top-bar.scss:
    #{} interpolation near operators will be simplified
    in a future version of Sass. To preserve the current behavior, use quotes:

  unquote("#{lower-bound($medium-range)}")

This is the most recent Sass and the most recent Foundation version
in the 5.x series, so just suppress this deprecation warning with
--quiet.  (We could go back to Sass 3.4.19, but part of the reason for
keeping up to date is that we've found that people will expect it to
work out-of-the-box with the most recent version of Sass.)