Fix migrations in Python 3
As documented in https://docs.djangoproject.com/en/1.8/topics/migrations/#supporting-python-2-and-3
Python 3 will create a bogus new migration to convert all
strings to Unicode if there's mixed bytes and Unicode strings
inside migrations.  Also, because of an oversight in
``to_field`` (https://code.djangoproject.com/ticket/24949),
the ``makemigrations`` command actually errors out in Python 3 with:

    AttributeError: 'bytes' object has no attribute ...

Unhelpfully, this doesn't say which migration's causing the issue,
so you've got to sift through all of them looking for bytes strings.
In any case, converting all strings to Unicode resolves both of these
issues.

Closes #847.